import os
from flask import Flask
app=Flask(__name__)
HTML="""<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{margin:0;padding:0;box-sizing:border-box;font-family:Arial}body{background:#0a0e14;color:#cdd6e3}
.header{padding:24px;text-align:center;background:radial-gradient(circle at center,#122033 0%,#0a0e14 70%)}
.lw{width:120px;height:120px;margin:0 auto 16px;background:radial-gradient(circle,#FFD700,#ff8c00);border-radius:50%;border:3px solid #FFD700;box-shadow:0 0 35px rgba(255,215,0,.7);display:flex;align-items:center;justify-content:center;font-size:50px}
.st{color:#FFD700;font-size:10px;letter-spacing:3px}.bt{color:#FFD700;font-size:22px;font-weight:800;margin:6px 0}.card{background:#111827;border:1px solid #1f2937;border-radius:12px;margin:12px 16px;padding:16px}
.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #1a2332;font-size:13px}.muted{color:#6b7a90;font-size:12px}
.off{background:#2a1212;color:#ff6b6b;padding:4px 10px;border-radius:6px;font-size:11px}.on{background:#0f2a1f;color:#4ade80;padding:4px 10px;border-radius:6px;font-size:11px}
.inp{background:#0e1520;border:1px solid #1f2d44;border-radius:8px;padding:10px;color:white;width:100%;margin:6px 0}.btn{background:linear-gradient(90deg,#FFD700,#ffae00);color:#000;border:none;padding:12px;border-radius:8px;width:100%;font-weight:800;margin-top:10px;cursor:pointer}
.btn2{background:#1f2937;color:#FFD700;border:1px solid #FFD700;padding:10px;border-radius:8px;width:100%;font-weight:700;margin-top:8px;cursor:pointer}
.slider{width:100%;accent-color:#FFD700}.pill{background:#0f2a1f;color:#4ade80;border-radius:12px;padding:2px 10px;font-size:12px;font-weight:700;cursor:pointer}.pill-off{background:#2a1212;color:#ff6b6b}
.log{background:#0a0e14;border:1px solid #1a2332;border-radius:8px;padding:8px;height:100px;overflow-y:auto;font-size:11px}
</style></head><body>
<div style="padding:12px 16px;display:flex;justify-content:space-between;border-bottom:1px solid #1a2332;font-size:12px"><span style="color:#6b7a90">reed.replit.dev</span><span id="topStatus" style="color:#ff4d4d">● Dashboard offline</span></div>
<div class="header"><div class="lw">🤖</div><div class="st">AUTOMATED MARKET MONITOR</div><div class="bt">Prince Gold Master V1</div><div style="font-size:11px;color:#8aa0b8">XM 411308190 LIVE</div></div>
<div class="card"><div style="font-size:10px;color:#6b7a90;letter-spacing:2px">LIVE INSTRUMENT</div><div style="font-weight:700">XAUUSD</div><div id="price" style="text-align:center;color:#FFD700;margin:12px;font-size:32px;font-weight:800">--</div><div class="muted" id="lastUpdate">Last update: Waiting</div></div>
<div class="card"><div style="display:flex;justify-content:space-between"><div><div style="font-size:10px;color:#6b7a90">CONNECTION</div><div id="connText" style="font-weight:700">OFFLINE</div></div><div id="dot" style="width:10px;height:10px;background:#ff4d4d;border-radius:50%"></div></div><div class="row"><span class="muted">Account</span><span id="accShow">XM 411308190</span></div><div class="row"><span class="muted">Ask</span><span id="askPrice">--</span></div><button class="btn" id="connectBtn" onclick="toggleConnect()">CONNECT NOW</button></div>
<div class="card"><div style="display:flex;justify-content:space-between"><div style="font-weight:700;font-size:13px">Bot activity</div><div class="muted" style="font-size:11px">Auto-refreshes every 2s</div></div><div id="botLog" class="log">Waiting...</div></div>
<div class="card"><div style="font-weight:700">Settings</div><div style="font-size:11px;color:#6b7a90;margin-bottom:8px">Connection and risk controls</div><div style="color:#FFD700;font-size:11px;margin:10px 0 4px">METAAPI CONNECTION</div><input id="accountId" class="inp" value="XM 411308190" oninput="saveSettings()"><select id="symbolSel" class="inp" onchange="saveSettings()"><option>XAUUSD</option><option>EURUSD</option><option>GBPUSD</option></select><input id="tokenInp" class="inp" placeholder="Paste token" type="password"><div style="margin:6px 0"><span id="statusBadge" class="off">● OFFLINE</span></div><div style="color:#FFD700;font-size:11px;margin:14px 0 4px">RISK SETTINGS</div><div style="display:flex;justify-content:space-between"><span class="muted">Lot Size</span><span style="color:#FFD700;font-weight:700" id="lotVal">0.01</span></div><input id="lotSlider" type="range" class="slider" min="0.01" max="1" step="0.01" value="0.01" oninput="updateLot(this.value)"><input id="slInp" class="inp" value="300"><input id="tpInp" class="inp" value="600"><input id="dlInp" class="inp" value="50"><div style="display:flex;justify-content:space-between;margin-top:8px"><span class="muted">Auto Lot</span><span id="autoPill" class="pill" onclick="toggleAuto()">ON</span></div><button class="btn2" onclick="alert('Saved!')">SAVE SETTINGS</button></div>
<script>
let online=false,price=2650.25,interval=null,autoLot=true;
function toggleConnect(){online=!online;const b=document.getElementById('connectBtn'),t=document.getElementById('connText'),d=document.getElementById('dot'),s=document.getElementById('statusBadge'),top=document.getElementById('topStatus');if(online){t.innerText='ONLINE';t.style.color='#4ade80';d.style.background='#4ade80';s.className='on';s.innerText='● ONLINE';top.innerText='● Dashboard online';top.style.color='#4ade80';b.innerText='DISCONNECT';b.style.background='#2a1212';b.style.color='#ff6b6b';interval=setInterval(()=>{price+=(Math.random()-0.5)*2;document.getElementById('price').innerText=price.toFixed(2);document.getElementById('askPrice').innerText=(price+0.35).toFixed(2);document.getElementById('lastUpdate').innerText='Last update: '+new Date().toLocaleTimeString();document.getElementById('botLog').innerHTML='<div>['+new Date().toLocaleTimeString()+'] Tick '+price.toFixed(2)+'</div>'+document.getElementById('botLog').innerHTML;},2000);}else{t.innerText='OFFLINE';t.style.color='white';d.style.background='#ff4d4d';s.className='off';s.innerText='● OFFLINE';top.innerText='● Dashboard offline';top.style.color='#ff4d4d';b.innerText='CONNECT NOW';b.style.background='linear-gradient(90deg,#FFD700,#ffae00)';b.style.color='#000';clearInterval(interval);document.getElementById('price').innerText='--';}}
function updateLot(v){document.getElementById('lotVal').innerText=v;}function toggleAuto(){autoLot=!autoLot;const p=document.getElementById('autoPill');p.innerText=autoLot?'ON':'OFF';p.className=autoLot?'pill':'pill pill-off';}
function saveSettings(){document.getElementById('accShow').innerText=document.getElementById('accountId').value;}
</script></body></html>"""
@app.route("/")
def home():
    return HTML
if __name__=="__main__":
    app.run(host="0.0.0.0",port=int(os.environ.get("PORT",10000)))
